# Generated by Django 4.2.9 on 2024-01-09 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('mail', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=16)),
                ('pseudo', models.CharField(max_length=16)),
                ('avatar', models.BinaryField()),
                ('user_is_connected', models.BooleanField(default=False)),
                ('user_is_in_game', models.BooleanField(default=False)),
                ('lose', models.PositiveIntegerField()),
                ('win', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('win_lose', models.PositiveIntegerField()),
                ('player1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_matches', to='api.user')),
                ('player2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_matches', to='api.user')),
            ],
        ),
    ]
