# Generated by Django 4.2.9 on 2024-01-13 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=50)),
                ('pseudo', models.CharField(max_length=16)),
                ('avatar', models.BinaryField(default=None, null=True)),
                ('user_is_connected', models.BooleanField(default=False)),
                ('user_is_in_game', models.BooleanField(default=False)),
                ('lose', models.PositiveIntegerField(default=0)),
                ('win', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('win_lose', models.PositiveIntegerField()),
                ('player1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_matches', to='api.profile')),
                ('player2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_matches', to='api.profile')),
            ],
        ),
    ]
