# Generated by Django 4.2.9 on 2024-01-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.BinaryField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lose',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='win',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
