# Generated by Django 4.2.9 on 2024-01-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
