# Generated by Django 4.2.9 on 2024-01-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_friends_delete_friendlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
