# Generated by Django 4.2.9 on 2024-01-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game_room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
