# Generated by Django 4.2.9 on 2024-01-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_game_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='paddle1_pos',
            field=models.PositiveIntegerField(default=55),
        ),
        migrations.AddField(
            model_name='match',
            name='paddle2_pos',
            field=models.PositiveIntegerField(default=55),
        ),
    ]
